version: "3.9"
name: "dhbw-docker-app"

services:
  api:
    build: ./api
    container_name: dhbw-api
    environment:
      NODE_ENV: development
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    networks:
      - net
      - data
#    ports:
#      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./api/src/migration:/app/src/migration:rw
    healthcheck:
      test: wget --no-verbose --spider -S -T 1 http://api:8080/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:alpine
    container_name: dhbw-db
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - data
    healthcheck:
      test: pg_isready -h db -p 5432 -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}
      interval: 30s
      timeout: 10s
      retries: 3

  proxy:
    image: nginx:alpine
    container_name: dhbw-proxy
    depends_on:
      api:
        condition: service_started
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "10000:80"
    networks:
      - net

networks:
  net:
  data:

volumes:
  db-data: